package com.example.AuditService.model;


public enum AuditAction {

    USER_LOGIN,
    USER_REGISTERED,

    ORGANIZATION_CREATED,
    ORGANIZATION_UPDATED,
    ORGANIZATION_DELETED,

    MEMBER_ADDED,
    MEMBER_REMOVED,
    MEMBER_ROLE_UPDATED,

    DOCUMENT_CREATED,
    DOCUMENT_VIEWED,
    DOCUMENT_UPDATED,
    DOCUMENT_DELETED,
    DOCUMENT_UPLOADED,

    AI_QUERY,

    SEARCH_PERFORMED,

    ROLE_CHANGED,
    PERMISSION_CHANGED
}