spring.application.name=document-service
server.port=8087

# ==================== EUREKA ====================

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true


# ==================== MONGODB ====================

spring.data.mongodb.uri=

# ==================== ACTUATOR ====================

management.endpoints.web.exposure.include=health,info

management.endpoint.health.show-details=always


# ==================== FILE UPLOAD ====================

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=25MB
